### ISSUE TITLE
DB sync failing to change directory

### ISSUE THREAD

**Issue by edjeavons** [jonbp/wp-cli-sync#1]
The database portion of the DB sync is failing for me. I think the SSH connection's commands should be joined with an `&&` on [this line](https://github.com/jonbp/wp-cli-sync/blob/d4bdcb281e844a0ea77db24859a18d6c3ef6b66f/wp-cli-sync.php#L68) (as opposed to a single `&`).

Using a single `&` runs the preceding command in the background. Can't explain why this works on some servers and not others but here's an example on a server which experiences it and I'd expect all servers to behave like this.

![image](https://user-images.githubusercontent.com/735284/68114547-2fda0680-feee-11e9-9efa-bba6db776ac9.png)

**Comment by jonbp** [comment]
Thanks! Pushed a fix in `1.1.2`
